# YAML example
# You can also use application.properties (see same folder)
aoaojiao:
  rpc:
    registry:
      serverAddr: 127.0.0.1:8848
      enabled: true
    client:
      loadBalancer: roundRobin
      faultTolerance: failFast
      retryTimes: 0
      rateLimit: 0
      circuitFailureThreshold: 3
      circuitOpenMillis: 3000
      timeoutMillis: 3000
